name: game_community
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.7
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  dots_indicator: ^4.0.1
  flutter_riverpod: ^3.0.3
  image_picker: ^1.2.1
  firestore_service_api: ^1.0.0
  firebase_storage: ^13.0.5
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/letter-J.png
    - assets/letter-M.png
    - assets/letter-V.png
